#!/bin/bash
relative_path='.'
while [[ $(realpath $relative_path) != '/' ]]; do
  #echo $(realpath $relative_path)
  if [[ -f "${relative_path}/gradlew" ]]; then
    #echo "Found gradlew at ${relative_path}"
    ${relative_path}/gradlew "$@"
    break
  fi
  if [[ -f "${relative_path}/settings.gradle" || -f "${relative_path}/settings.kts" || -f "${relative_path}/settings.gradle.kts" ]]; then
    break
  fi
  relative_path="${relative_path}/.."
done
if [[ $(realpath $relative_path) = '/' ]]; then
  echo "gradlew not found"
fi
